services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=runner
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
      - POSTGRES_DB=testdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: >
      bash -c "docker-entrypoint.sh postgres &
      sleep 10 &&
      psql -U runner -d mydb -c 'CREATE DATABASE testdb;' &&
      wait"
      
  # testdb:
  #   image: postgres:16
  #   depends_on:
  #     - postgres
  #   command: >
  #     bash -c "docker-entrypoint.sh postgres &
  #     psql -U runner -d mydb -c 'CREATE DATABASE testdb;' &&
  #     wait"

      
  # postgres_test:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_DB=testdb
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5433:5433'

volumes:
  postgres:
  # postgres_test:
