services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=runner
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nest_grahpql_mydb
      - POSTGRES_DB=nest_grahpql_testdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: >
      bash -c "docker-entrypoint.sh postgres &
      sleep 10 &&
      psql -U runner -d mydb -c 'CREATE DATABASE nest_grahpql_testdb;' &&
      wait"

volumes:
  postgres:
